### ISSUE TITLE
Support Sequences as return type

### ISSUE THREAD

**Issue by JackieWeiss** [status-im/nim-ethers#16]
Currently there doesn't appear to be a way to have a sequence as the return type for a function.
With a contract like
```solidity
contract Test{
    uint256[] foo = [1, 2, 3];
    function getfoo() external view returns(uint256[] memory){
        return foo;
    }
```
and the nim proc
```nim
proc getfoo(contract: Test): seq[UInt256] {.contract, view.}
```
calling getfoo results in a
`Error: unhandled exception: unable to decode return value as seq[UInt256] [ContractError]`

**Comment by markspanbroek** [comment]
Fixed in version 0.1.8
