### ISSUE TITLE
Allow enums in functions

### ISSUE THREAD

**Issue by JackieWeiss** [status-im/nim-ethers#19]
A function with an enum as a parameter fails to compile. The equivalent with a uint8 instead of the enum works perfectly. Allow enums as a function parameter as enums as a return type are already supported.
```nim
# Fails to compile
proc getfoo(contract: Test, foo: FooEnum): UInt256 {.contract, view.}

# Works
proc getfoo(contract: Test, foo: uint8): UInt256 {.contract, view.}

#Also works
proc getfoo(contract: Test): FooEnum {.contract, view.}
```

**Comment by markspanbroek** [comment]
Fixed in version 0.1.9.
