### ISSUE TITLE
Remove dependency on `nim-eth`?

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-ethers#32]
We may want to remove dependency on `nim-eth` (used in wallet functionality) and replace with another crypto lib, so that we can retain support for `nim-codex` without needing to add a new dependency in that project. However, it makes sense for `nim-ethers` as a lib to use `nim-eth` and its key functionality. Not sure how we want to proceed.

Also tracked in https://github.com/status-im/nim-codex/issues/220.

**Comment by markspanbroek** [comment]
Closing this, because that we've re-added `nim-eth` in codex: https://github.com/status-im/nim-codex/pull/236.
